person:
  lastName: 张三
  age: 18
  boss: false
  birth: 2020/2/8
  maps: {k1: v1,k2: v2}
  lists:
   - lisi
   - zhouliu
  dog:
    name: 小狗
    age: 3

spring:
  profiles:
    active: dev7

---
server:
  port: 8888
spring:
  profiles: dev8
---
server:
  port: 9999
spring:
  profiles: prod

---
server:
  port: 7777
spring:
  profiles: dev7

