server:
  port: 8082

#spring:
#  datasource:
#    data-username: root
#    data-password: riit
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UT
#    driver-class-name: com.mysql.jdbc.Driver
spring:
  datasource:
    password: riit
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&characterEncoding=utf8
    username: root

mybatis:
# 指定sql映射文件的位置 --所有的mapper映射文件
  mapper-locations: classpath:mapping/*Mapper.xml
#  指定全局配置文件的位置 --定义所有操作类的别名所在包
  type-aliases-package: com.yes.springbootmybatis.mapper

#showSql
logging:
  level:
    com:
      example:
        mapper :

